version: "2.1"
services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /srv/dev-disk-by-uuid-f45f93a3-9045-4f75-b911-36c7243bf0c8/Docker/heimdall/config:/config
    ports:
      - 9001:80
      - 40443:443
    restart: unless-stopped

